# Shared helpers for the pico toolchain installers.
# Sourced by install.sh — not meant to be executed directly.

info() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33mwarning:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# Run a privileged command; skips sudo when already root (e.g. in containers).
as_root() {
  if [[ ${EUID} -eq 0 ]]; then "$@"; else sudo "$@"; fi
}

# Clone or update pico-sdk at the pinned tag. Idempotent: re-running with the
# same version is a no-op, with a new version it fetches and switches tags.
clone_pico_sdk() {
  if [[ -d "$PICO_SDK_PATH/.git" ]]; then
    local current
    current="$(git -C "$PICO_SDK_PATH" describe --tags --always)"
    if [[ "$current" == "$PICO_SDK_VERSION" ]]; then
      info "pico-sdk $PICO_SDK_VERSION already present at $PICO_SDK_PATH"
      return
    fi
    info "switching pico-sdk at $PICO_SDK_PATH from $current to $PICO_SDK_VERSION"
    git -C "$PICO_SDK_PATH" fetch --tags origin
  else
    info "cloning pico-sdk $PICO_SDK_VERSION into $PICO_SDK_PATH"
    mkdir -p "$(dirname "$PICO_SDK_PATH")"
    git clone https://github.com/raspberrypi/pico-sdk.git "$PICO_SDK_PATH"
  fi
  git -C "$PICO_SDK_PATH" checkout --quiet "$PICO_SDK_VERSION"
  git -C "$PICO_SDK_PATH" submodule update --init
}

# Build picotool from source into $PICO_ROOT/bin. Source builds behave the
# same on every platform, unlike distro packages which vary in availability.
install_picotool() {
  local bin="$PICO_ROOT/bin/picotool"
  if [[ -x "$bin" ]] && "$bin" version 2>/dev/null | grep -q "$PICOTOOL_VERSION"; then
    info "picotool $PICOTOOL_VERSION already installed at $bin"
    return
  fi

  local src="$PICO_ROOT/src/picotool"
  if [[ ! -d "$src/.git" ]]; then
    info "cloning picotool $PICOTOOL_VERSION"
    mkdir -p "$(dirname "$src")"
    git clone https://github.com/raspberrypi/picotool.git "$src"
  else
    git -C "$src" fetch --tags origin
  fi
  git -C "$src" checkout --quiet "$PICOTOOL_VERSION"

  info "building picotool"
  cmake -S "$src" -B "$src/build" -DPICO_SDK_PATH="$PICO_SDK_PATH"
  cmake --build "$src/build" --parallel
  mkdir -p "$PICO_ROOT/bin"
  cp "$src/build/picotool" "$bin"
  info "picotool installed to $bin"

  if [[ "$(uname -s)" == "Linux" ]]; then
    info "to use picotool without sudo, install the udev rules:"
    info "    sudo cp $src/udev/99-picotool.rules /etc/udev/rules.d/"
  fi
}

# Write a small env file the user sources from their shell. We never edit
# shell rc files ourselves — the user opts in by sourcing this.
write_env_file() {
  mkdir -p "$(dirname "$PICO_ENV_FILE")"
  cat > "$PICO_ENV_FILE" <<EOF
# Generated by the pico-sdk-template toolchain installer.
# Source this from your shell or add it to your shell startup file:
#   source $PICO_ENV_FILE
export PICO_SDK_PATH="$PICO_SDK_PATH"
case ":\$PATH:" in
  *":$PICO_ROOT/bin:"*) ;;
  *) export PATH="$PICO_ROOT/bin:\$PATH" ;;
esac
EOF
  info "environment file written to $PICO_ENV_FILE"
}

# Report what is present and what is missing. Returns nonzero if anything
# required for a pico-sdk build is missing.
check_toolchain() {
  local missing=0 tool
  for tool in git cmake python3 arm-none-eabi-gcc; do
    if command -v "$tool" >/dev/null 2>&1; then
      info "found: $tool ($(command -v "$tool"))"
    else
      warn "missing: $tool"
      missing=1
    fi
  done

  if command -v ninja >/dev/null 2>&1 || command -v make >/dev/null 2>&1; then
    info "found: build tool ($(command -v ninja 2>/dev/null || command -v make))"
  else
    warn "missing: ninja or make"
    missing=1
  fi

  if [[ -e "$PICO_SDK_PATH/pico_sdk_init.cmake" ]]; then
    info "found: pico-sdk at $PICO_SDK_PATH"
  else
    warn "missing: pico-sdk at $PICO_SDK_PATH"
    missing=1
  fi

  return "$missing"
}
